### ISSUE TITLE
figure out how font specifications in pango work

### ISSUE THREAD

**Issue by doy** [doy/runes#48]
Why does "7x14" not work? It seems like the only way to actually get that font is via "Fixed 10.5", which seems less than ideal.

**Comment by jmarca** [comment]
Gave a quick build/run whirl to this, and ran into a font issue.  Not sure this is the right issue,  but on my retina display macbook pro (running linux) runes has the "micro-small font" problem.  I typically use 

      Xft*dpi:              150

in my .Xdefaults file to get around this, but I gather that means using xft fonts, which you mention not implementing above.
